version: 2

models:
  - name: airbnb_transformed
    description: "Cleaned and standardized Airbnb listing data."
    columns:
      - name: host_id
        description: "Unique identifier for the host."
        tests:
          - not_null
      - name: price
        description: "Price per night in USD for the listing."
        tests:
          - not_null
      - name: neighborhood
        description: "Name of the neighborhood where the listing is located."
        tests:
          - not_null
      - name: room_type
        description: "Type of room offered (Entire home, Private room, etc.)"
        tests:
          - not_null
      - name: availability_365
        description: "Number of days the listing is available per year."
